language: ruby
sudo: false
node_js:
  - "0.12"
  - "4"
  - "5"
before_script:
  - gem install sass
  - npm install
  - npm install bower -g && bower install sass-mq/sass-mq#$TRAVIS_BRANCH
script:
  - npm test
